### ISSUE TITLE
globalObj.setTimeout is not a function when upgrading from version 7.2.0

### ISSUE THREAD

**Issue by henrymoulton** [callstack/react-native-testing-library#1116]
## Describe the bug

When upgrading from 7.2.0 to version 9 I encounter errors related to `setTimeout` in my tests:

```
    TypeError: (0 , _timers.setTimeout) is not a function

      at call (node_modules/@testing-library/react-native/build/waitFor.js:48:33)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator._invoke (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.call (node_modules/regenerator-runtime/runtime.js:118:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:154:20)
      at node_modules/regenerator-runtime/runtime.js:189:11
      at callInvokeWithMethodAndArg (node_modules/regenerator-runtime/runtime.js:188:16)
      at AsyncIterator.enqueue (node_modules/regenerator-runtime/runtime.js:211:13)
```

and 

```
    TypeError: globalObj.setTimeout is not a function

      at setImmediatePolyfill (node_modules/@testing-library/react-native/build/helpers/timers.js:59:20)
      at Object.then (node_modules/@testing-library/react-native/build/flushMicroTasks.js:26:7)
```

## Expected behavior

Should run

## Steps to Reproduce

I noticed this error came up with https://github.com/callstack/react-native-testing-library/issues/702#issuecomment-801934900 but I can't see anywhere that I'm mocking window.

## Versions

```
  npmPackages:
    @testing-library/react-native: 9.1.0 => 9.1.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-test-renderer: 17.0.2 => 17.0.2 
```

**Comment by mdjastrzebski** [comment]
Closing as non-actionable. Without repro we cannot do anything more.
