### ISSUE TITLE
v14 "hides" expo-router's extended jest matchers like `toHavePathname`

### ISSUE THREAD

**Issue by kovbe21** [callstack/react-native-testing-library#1924]
## Describe the bug

On expo and expo-router v55 (v56 also), testing library v14.

Expo router has extended jest matchers like `toHavePathname`. See docs: https://docs.expo.dev/router/reference/testing/#jest-matchers

After updating to v14, these matchers are no longer working, throwing TypeError.

Example reproduction repository: https://github.com/kovbe21/jest-reproductions (path-name.test.tsx)

Not sure whether an expo-router, or react-native-testing-library bug, will report it to expo as well, but the problem has been introduced with react-native-testing-library v14. On v13 it was working fine.

## Expected behavior

When using expo-router's extended matchers, it should not throw error, and match the expected pathname.

## Steps to Reproduce

Example reproduction repository: https://github.com/kovbe21/jest-reproductions
- Run test named `path-name.test.tsx`

OR:

- set up expo-router testing according to docs: https://github.com/kovbe21/jest-reproductions
- Add a test like below
- See the test fail.

```
it('expo-router test should pass', async () => {
  const MockComponent = jest.fn(() => <View />);

  await renderRouter(
    {
      index: MockComponent,
      'directory/a': MockComponent,
      '(group)/b': MockComponent,
    },
    {
      initialUrl: '/directory/a',
    }
  );

  // TypeError: screen.getPathname is not a function
  expect(screen).toHavePathname('/directory/a');
});

```

## Versions

  npmPackages:
    @testing-library/react-native: ^14.0.1 => 14.0.1 
    react: 19.2.0 => 19.2.0 
    react-native: 0.83.6 => 0.83.6 
    test-renderer: ^1.2.0 => 1.2.0

**Comment by mdjastrzebski** [comment]
@kovbe21 that seems like something on Expo Router (ER) side. 

Afair RNTL Jest matchers are registered in the same way in v13 and v14. The `screen` object mentioned in error message is RNTL object and does not have, and never had, `getPathname` method, which seems like something coming from ER.

**Comment by kovbe21** [comment]
Hi @mdjastrzebski! 

Thanks for the response! Something surely has changed, since v13 is working fine, v14 has this error only. Maybe a solution was used by ER that unorthodox, and now not working.

I will report it to ER also, until that for anybody who run into this, I could fix it by Adding the following lines to jest's `setup-files-after-env`

```
// Ensure expo-router testing utilities are initialized (registers `screen.getPathname` and matchers)
import 'expo-router/testing-library';

// Provide robust matchers that read directly from the router store.
try {
  const matchers = require('expect/build/matchers').default;
  const routerStore = require('expo-router/build/global-state/router-store');

  expect.extend({
    toHavePathname() {
      return matchers.toEqual(routerStore.store.getRouteInfo().pathname, arguments[1]);
    },
    toHavePathnameWithParams() {
      return matchers.toEqual(routerStore.store.getRouteInfo().pathnameWithParams, arguments[1]);
    },
    toHaveSegments() {
      return matchers.toEqual(routerStore.store.getRouteInfo().segments, arguments[1]);
    },
    toHaveSearchParams() {
      return matchers.toEqual(routerStore.store.getRouteInfo().params, arguments[1]);
    },
    toHaveRouterState() {
      return matchers.toEqual(routerStore.store.state, arguments[1]);
    },
  });
} catch {
  // ignore if expect internals aren't available
}

```

**Comment by henriquepe** [comment]
FYI: a fix for this is now up on the Expo side — expo/expo#48587 makes `expo-router/testing-library` compatible with both RNTL v13 and v14. Root cause was `renderRouter` assigning the route helpers (`getPathname`, etc.) onto the return value of `render()` — which became a promise in v14, so the helpers never reached the object RNTL registers as `screen`. Until it lands, pinning RNTL to v13 remains the workaround.

**Comment by mdjastrzebski** [comment]
Closing then
