### ISSUE TITLE
Unable to pass waitFor tests

### ISSUE THREAD

**Issue by alexborton** [callstack/react-native-testing-library#702]
Previously, we have been using the original `react-native-testing-library` library and `flushMicrotasksQueue` to progress our tests, waiting for something synchronous to update.

In migrating to the latest version of `@testing-library/react-native` (`^7.2.0`), `flushMicrotasksQueue` has been deprecated and will soon be removed. The obvious stand in is `waitFor`, but i am struggling to find why my (simple) tests are failing with this method implemented. 

Here is an example;

```
// Original test...

 ...
  it('returns the loading prop as true until the fetch has been completed successfully, turning it to false', async () => {
    const { getByText, unmount } = render(
      <AttachmentDownloadContainer {...mockProps}>
        {({ loading }) => <Text>{loading ? 'loading' : 'notloading'}</Text>}
      </AttachmentDownloadContainer>,
    )
    expect(getByText(/loading/))
    await flushMicrotasksQueue()
    expect(getByText(/notloading/))
    unmount()
  })
...
```

This passes as expected, but warns about `flushMocrotastsQueue()` as we would expect...

```
// New test...

  it('returns the loading prop as true until the fetch has been completed successfully, turning it to false', async () => {
    const { getByText, unmount } = render(
      <AttachmentDownloadContainer {...mockProps}>
        {({ loading }) => <Text>{loading ? 'loading' : 'notloading'}</Text>}
      </AttachmentDownloadContainer>,
    )
    expect(getByText(/loading/))
    await waitFor(() => {
      expect(getByText(/notloading/))
    })
    unmount()
  })
```

This test fails. It never finds the `notloading` text. But strangely, if i change that assertion inside the `waitFor` to look for `loading`, it also fails...

```
    await waitFor(() => {
      expect(getByText(/loading/))
    })
```

It seems like nothing is found in my `waitFor` which, to me, suggests something wrong with my setup somewhere.

These tests are without the context of the component itself, but it's basically making a request on mount and updating some state as it goes (in redux, but that shouldn't matter). We are also mocking the request response like so...

```
beforeEach(() => {
  requestUtils.request = jest.fn(() => Promise.resolve(shimAttachmentFixture))
})

afterEach(() => {
  requestUtils.request.mockClear()
})
```

`shimAttachmentFixture` is a JSON response. 

Just to reiterate - these tests were/do pass when using the `flushMicrotasksQueue` - what am i missing...?

**Comment by thymikee** [comment]
Have you tried `await findByText()`? https://callstack.github.io/react-native-testing-library/docs/api-queries/#findby

**Comment by thymikee** [comment]
Can you create a repro we could download? Also please try to call `debug` to see if the text is actually there

**Comment by timbastin** [comment]
Hey, @alexborton I just faced exactly the same issue you are experiencing. I did some troubleshooting and figured out, that removing `jest.useFakeTimers`fixes the issue. Maybe you are calling it as well somewhere. Probably @thymikee has a better idea to solve this.

**Comment by thymikee** [comment]
If this is related to fake timers, please upgrade to `8.0.0-rc.0`

**Comment by timbastin** [comment]
I just tried but:

```
TypeError: globalObj.setTimeout is not a function

      at setImmediatePolyfill (node_modules/@testing-library/react-native/build/helpers/timers.js:59:20)
      at Object.then (node_modules/@testing-library/react-native/build/flushMicroTasks.js:26:32)
```

And

```
TypeError: (0 , _timers.setTimeout) is not a function
 at node_modules/@testing-library/react-native/build/waitFor.js:47:56
      at tryCallTwo (node_modules/react-native/node_modules/promise/lib/core.js:45:5)
      at doResolve (node_modules/react-native/node_modules/promise/lib/core.js:200:13)
      at new Promise (node_modules/react-native/node_modules/promise/lib/core.js:66:3)
      at waitForInternal (node_modules/@testing-library/react-native/build/waitFor.js:43:10)
      at node_modules/@testing-library/react-native/build/waitFor.js:196:20
      at batchedUpdates (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12395:12)
      at act (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14936:14)
      at Function.waitFor (node_modules/@testing-library/react-native/build/waitFor.js:195:26)
```

**Comment by timbastin** [comment]
You are right. I was indeed mocking the window object. This does fix the issue.

**Comment by alexborton** [comment]
@timbastin It was indeed `jest.useFakeTimers()` which runs before all my tests (according to my notes, to stop Animations behaving strangely)

@thymikee I removed `jest.useFakeTimers()` and `waitFor` (and `findBy`) worked as expected 🎉  I also upgraded to `8.0.0-rc` and popped `jest.useFakeTimers()` back in and it still works as expected 😎 

Thank you to you both 🙏

**Comment by pke** [comment]
I can confirm that `waitFor` and `findBy` are broken in 7.1.0. 

// Does not work in 7.1.0 but works in 8.0.0-rc.1
```
act(() => jest.advanceTimersToNextTimer())
await waitFor(() => findByText("text"))
```

Any idea what's going on?

**Comment by AugustinLF** [comment]
Closing since the initial issue has been resolved. If there's a different problem please create a dedicated issue.
