### ISSUE TITLE
Rejected Promises in test causes test to "fail" with error ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

### ISSUE THREAD

**Issue by nero2009** [callstack/react-native-testing-library#1444]
## Describe the bug

I just upgraded from react native 0.70 to 0.72 and some of my tests that used to pass on my CI started to fail. The test suite passses but the test exits with an error.

```

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From App.test.js.

      19 |     console.log('ran 2344')
      20 |     } catch (error) {
    > 21 |       Alert.alert('Error', error)
         |       ^
      22 |     }
      23 |    
      24 |   }

      at Object.get Alert [as Alert] (node_modules/react-native/index.js:94:12)
      at Alert (App.js:21:7)
          at Generator.throw (<anonymous>)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
/Users/mac/Documents/work/side/failedPromises/App.js:26
        _reactNative.Alert.alert('Error', error);
                           ^

TypeError: _reactNative.Alert.alert is not a function
    at /Users/mac/Documents/work/side/failedPromises/App.js:26:28
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/mac/Documents/work/side/failedPromises/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (/Users/mac/Documents/work/side/failedPromises/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```
## Expected behavior

Expected bahavior is for this not to break the CI but maybe throw a warning

## Steps to Reproduce

- clone https://github.com/nero2009/promise-reject-repro
- install deps
- run `npm run test`
- 

## Versions

npmPackages:
    @testing-library/react-native: ^12.2.0 => 12.2.0 
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.3 => 0.72.3 
    react-test-renderer: ^18.2.0 => 18.2.0

**Comment by mdjastrzebski** [comment]
@nero2009 is this actual RNTL issue? You mentioned that this happened after RN version upgrade. As a rule, testing code should wait for async code, e.g. promises, to resolve before ending the tests. Therefore, you should add `await findBy*` or `await waitFor(() => expectation))`  to wait for that promise to resolve. You can also use Jest fake timers and run the times using `jest.runAllTimers()`.

**Comment by michtntbrighte** [comment]
my tests is also failing after upgrading to RN v0.72

**Comment by pierrezimmermannbam** [comment]
It's difficult to see what could be the cause of this issue without further information. Tests pass in the RNTL repo after upgrading to v72. Could you provide a reproduction of the bug so that we can investigate? You can use the [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic) as a starting point
