### PR TITLE
fix: resolve AccessibilityState import issue due to types migration to `react-native` package

### LINKED ISSUE #1351: Type error when upgrading from 11.5 to 11.5.1 with skipLibCheck: false and using RN 0.70
## Describe the bug

While trying to upgrade to the RC (anyone could link me the thread where we were discussing the RC, I can't find it anymore), I realised I missed some minors updates, and found breaking types between `11.5.0` and `11.5.1`.

```
node_modules/@testing-library/react-native/build/within.d.ts:48:152 - error TS2307: Cannot find module 'react-native/types' or its corresponding type declarations.

48     getAllByRole: import("./queries/makeQueries").GetAllByQuery<import("./matches").TextMatch, import("./queries/options").CommonQueryOptions & import("react-native/types").AccessibilityState & {
                                                                                                                                                          ~~~~~~~~~~~~~~~~~~~~

...

18  node_modules/@testing-library/react-native/build/render.d.ts:51
18  node_modules/@testing-library/react-native/build/within.d.ts:32
```

All errors are regarding the way the import of `AccessibilityState`  is done as part of our build output.

## Steps to Reproduce

Simply create a repo with RN@0.70 and a version of RNTL>=11.5.1, make sure to have `skipLibCheck: false` in the `compilerOptions` of your tsconfig and run typescript.

## Versions

```
  npmPackages:
    @testing-library/react-native: 12.0.0-rc.0 => 12.0.0-rc.0
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-test-renderer: 18.1.0 => 18.1.0
```

### PR DESCRIPTION
**Pull request by mdjastrzebski**
### Summary

Duplicate `AccessibilityState` type as `AccessibilityStateMatcher` type in order to avoid issues occurring during migration period from `@types/react-native` to built-in `react-native` types. See #1351 for details.

This fix will be first applied to v12 branch to verify that it fixes the issue, and later will be backported to v11.

Resolves #1351

### Test plan

Verification by @AugustinLF after v12 RC2 is released.

### CODE REVIEW

**Comment by mdjastrzebski** [comment]
@thymikee perhaps you'll have some alternative solution to the exposing RN types issue during migration from `@types/react-native` to built-in `react-native` type defs.

**Comment by pierrezimmermannbam** [comment]
We're also using `AccessibilityValue` type from React Native

**Comment by mdjastrzebski** [comment]
@pierrezimmermannbam true, but somehow we use it only internally and do not re-export it. When searching in `build` folder there are no more any `import("react-native")` nor `import("react-native/types")` statements in `.d.ts` files.

**Review by AugustinLF — APPROVED** [review]

**Comment by AugustinLF** [comment]
Yep the errors I saw were only pointing out to `AccessibilityState`

**Comment by pierrezimmermannbam** [comment]
Oh indeed we're redeclaring the type `AccessibilityValueMatcher` so it's not a problem

**Review by pierrezimmermannbam — APPROVED** [review]

**Comment by mdjastrzebski** [comment]
Just released RC2 with this fix. @AugustinLF let me know if this fixes the error, then I will backport it to v11 versions on `main` branch.
